"""Initial Migration

Revision ID: 9950b8736634
Revises: 8fe19bd94e28
Create Date: 2022-04-04 02:10:26.027602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9950b8736634'
down_revision = '8fe19bd94e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracker_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )
    op.drop_table('logs')
    op.drop_table('trackers')
    # ### end Alembic commands ###
